# policy/src/llm_policy/thresholds/extract/default.yaml
version: "v1"
task: null

metrics:
  schema_validity_rate:
    min: 0.90

  required_present_rate:
    min: null

  doc_required_exact_match_rate:
    min: null

  latency_p95_ms:
    max: null

  latency_p99_ms:
    max: null

params:
  min_n_total: 20
  min_field_exact_match_rate: {}

  # If you still want these around for other policies, keep them in params.
  # If nothing uses them anymore, delete them.
  max_error_rate: 0.05
  max_5xx_rate: 0.01
  max_transport_error_rate: 0.01