apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm

resources:
  - ../../base

configMapGenerator:
  - name: llm-models
    files:
      - models.yaml=models.observability-proof.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: server-patch.yaml
  - path: policy-job-disable.yaml
  - path: ingress-disable.yaml
