"""sync schema after refactor

Revision ID: 8acc77092594
Revises: bdd9204b32d2
Create Date: 2026-02-07 11:24:32.973838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acc77092594'
down_revision: Union[str, Sequence[str], None] = 'bdd9204b32d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns (safe defaults so existing rows get populated)
    op.add_column(
        "inference_logs",
        sa.Column("status_code", sa.Integer(), server_default=sa.text("200"), nullable=False),
    )
    op.add_column(
        "inference_logs",
        sa.Column("cached", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("inference_logs", sa.Column("error_code", sa.String(length=64), nullable=True))
    op.add_column("inference_logs", sa.Column("error_stage", sa.String(length=64), nullable=True))

    # Indexes
    op.create_index(op.f("ix_inference_logs_error_code"), "inference_logs", ["error_code"], unique=False)
    op.create_index(op.f("ix_inference_logs_error_stage"), "inference_logs", ["error_stage"], unique=False)
    op.create_index(op.f("ix_inference_logs_status_code"), "inference_logs", ["status_code"], unique=False)
    op.create_index("ix_inflog_route_created", "inference_logs", ["route", "created_at"], unique=False)
    op.create_index("ix_inflog_status_created", "inference_logs", ["status_code", "created_at"], unique=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inflog_status_created', table_name='inference_logs')
    op.drop_index('ix_inflog_route_created', table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_status_code'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_error_stage'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_error_code'), table_name='inference_logs')
    op.drop_column('inference_logs', 'error_stage')
    op.drop_column('inference_logs', 'error_code')
    op.drop_column('inference_logs', 'cached')
    op.drop_column('inference_logs', 'status_code')
    # ### end Alembic commands ###
